name: 'Terraform CD'

on:
  push:
    branches:
      - 'main'
    paths:
      - infrastructure/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to deploy to'
        required: true
        default: dev
        options:
        - dev
        - test
        - prod

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.plan.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.6

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init

      - name: Terraform Workspace
        working-directory: ./infrastructure
        run: |
          if [ ${{ github.event_name }} = 'workflow_dispatch' ];
          then
            terraform workspace select ${{ github.event.inputs.environment }}
          else
            terraform workspace select dev
          fi

      - name: Terraform Plan
        id: plan
        working-directory: ./infrastructure
        run: terraform plan -input=false -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./infrastructure/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    if: ${{ needs.plan.outputs.status }} == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ./infrastructure

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.6

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init

      - name: Terraform Workspace
        working-directory: ./infrastructure
        run: |
          if [ ${{ github.event_name }} = 'workflow_dispatch' ];
          then
            terraform workspace select ${{ github.event.inputs.environment }}
          else
            terraform workspace select dev
          fi

      - name: Terraform Apply
        working-directory: ./infrastructure
        run: terraform apply -input=false tfplan
