name: 'Terraform CI'

on:
  push:
    branches:
      - '**'
    paths:
      - infrastructure/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to deploy to'
        default: dev
        options:
        - dev
        - test
        - prod

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init

      - name: Terraform Workspace
        working-directory: ./infrastructure
        run: |
          if [ ${{ github.event_name }} = 'workflow_dispatch' ];
          then
            terraform workspace select ${{ github.event.inputs.environment }}
          else
            terraform workspace select dev
          fi

      - name: Terraform Format
        working-directory: ./infrastructure
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./infrastructure
        run: terraform validate -no-color

      - name: TFLint Setup
        uses: terraform-linters/setup-tflint@v1

      - name: TFLint Init
        working-directory: ./infrastructure
        run: tflint --init

      - name: TFLint Validate
        working-directory: ./infrastructure
        run: tflint --format=compact --config=.tflint.hcl

      - name: Checkov Validate
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./infrastructure
          download_external_modules: true
          framework: terraform
